#! /bin/bash
#!/bin/bash
if [ "$1" = "photonic_SSL" ]; then
    python3 "src/$1/main.py" --quantum
elif [ "$1" = "GLASE" ]; then
    python3 "src/GLASE/train.py"
elif [ "$1" = "AnnotCNN" ]; then
    python3 "src/AnnotCNN/main.py" hybrid
else
    python3 "src/$1/main.py"
fi